title: "Dark Souls 1 Clips of the Week"
category-id: "20" # gaming category id
game-id: "29433"
first: 15
days: 7
database: "ds1-clips.sqlite"
description: "Dark Souls 1 Clips of the Week!\nIf you are featured in this channel's videos and wish to be removed, feel free to email me at soulsarchives@gmail.com\n\n#SoulsArchives #DS1 #Gaming #Twitch\n\n"
tags: "DS1,Twitch,Dark Souls,Dark Souls Remastered"
