name: Go

on:
  push:
    branches: [ "main", "v2" ]
  pull_request:
    branches: [ "main", "v2" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Fmt
      run: go fmt -v ./...
      
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Your Name
        author_email: mail@example.com
        message: 'github actions: formatted go files'
        add: '*.go'
